spring:
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET_KEY:my-local-secret-key-12345678901234567890}
  expiration: 36000000

cors:
  allowed-origins: "http://localhost:5173"

logging:
  level:
    root: INFO
